name: release pipeline

on:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    name: test package with Python ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install .      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: test OGG auto          
        run: |
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.ogg          
      - name: install ffmpeg
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test MP3 auto
        run: |          
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.mp3 
      - name: test choice
        run: |          
          yes 3 | ytdlmusic "the beatles" "let it be"
          test -f the_beatles_let_it_be_1.mp3
      - name: test diff
        run: |          
          md5sum the_beatles_let_it_be.mp3
          md5sum the_beatles_let_it_be_1.mp3
          echo "les md5 doivent etre differents"
          test "$(md5sum the_beatles_let_it_be.mp3)" != "$(md5sum the_beatles_let_it_be_1.mp3)"

  push:
    needs: test
    name: push package on pypi
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'    
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip        
      - name: install pep517
        run: |
          pip install pep517
      - name: build
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
