name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10-dev' ]
    name: test package with ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install .      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: test OGG auto          
        run: |
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.ogg          
      - name: install ffmpeg
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test MP3 auto
        run: |          
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.mp3 
      - name: test choice
        run: |          
          yes 3 | ytdlmusic "the beatles" "let it be"
          test -f the_beatles_let_it_be_1.mp3
      - name: test diff
        run: |          
          md5sum the_beatles_let_it_be.mp3
          md5sum the_beatles_let_it_be_1.mp3
          echo "les md5 doivent etre differents"
          test "$(md5sum the_beatles_let_it_be.mp3)" != "$(md5sum the_beatles_let_it_be_1.mp3)"
